### ISSUE TITLE
Add possibility to convert already downloaded zip archive.

### ISSUE THREAD

**Issue by SirWindfield** [kriegaex/Galileo-Openbook-Cleaner#29]
I wanted to download the C von A bis Z book but your program always says that the md5 sum is wrong and stops with an exception. Would be nice if you could add the feature to convert a already downloaded archive so problems like those cannot happen ...

**Comment by kriegaex** [comment]
The feature already exists. This question has been asked many times before.

Just run the program again without deleting the download, it will be converted without any problems. Another option is to use `--write-config` and edit the MD5 in the config file so as to avoid the checksum problem next time you start from scratch. Sometimes the publisher changes existing books which leads to different MD5 checksums. I am not actively maintaining the program at the moment, but it is easy to help yourself.

BTW, I created #25 a while ago in order to to forget to make this part of the program more user-friendly.
